using AnnuaireEntreprise.Maui.Services.Employee;
using AnnuaireEntreprise.Maui.Services.Service;
using AnnuaireEntreprise.Maui.Services.Site;
using AnnuaireEntreprise.Maui.ViewModels;
using AnnuaireEntreprise.Maui.Views;
using CommunityToolkit.Maui.Views;

namespace AnnuaireEntreprise.Maui;

public partial class MainPage : ContentPage
{
	// This method is usually generated by the XAML compiler

	public MainPage()
	{
		InitializeComponent();

		// Set the BindingContext for data binding
		BindingContext = new MainPageViewModel();
	}
	private void OnSearchButtonClicked(object sender, EventArgs e)
	{
		var popup = new SearchEmployeePopup();
		this.ShowPopup(popup);
	}

}

